# Generated by Selenium IDE
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestclick():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_testclick(self):
    self.driver.get("https://leetcode.cn/")
    self.driver.find_element(By.CSS_SELECTOR, "#headlessui-menu-button-\\:R79akd6\\: > svg").click()
    self.driver.set_window_size(1552, 840)
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.LINK_TEXT, "交流丨想交一个只聊技术的朋友").click()
    self.vars["win955"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win955"])
    element = self.driver.find_element(By.CSS_SELECTOR, ".css-em3qpz-QuestionTitle picture")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".css-1rqd8vn-layer1-card-AnswerDetailWrapper:nth-child(1) .css-wr5fku-HiddenWrapper .es3xzeu0 > span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
  
